# docker-compose.yml
version: '3.8'

services:
  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    command: "celery -A tasks.celery_app worker --loglevel=info"