# docker-compose.yml
version: '3.8'

services:
  scraper-test:
    build: .
    # This command overrides the CMD in the Dockerfile
    # It tells the container to run our scraper script directly
    command: python scraper.py